### PR TITLE
Reworked files writing behavior: new file per each new song

### PR DESCRIPTION
**Pull request by zugzug90**
This implementation is an answer to current issue: https://github.com/jeremycryan/pytchie/issues/2

# What have been changed here?
Reworked files writing behavior: new file per each new song with an increasing counter suffix

# Plans to do
1. Planning to add checkbox for altering between desired behaviors: `overwrite mode` vs. `new file per each new song`.
2. Showing name of the file to be generated in bottom progress bar somewhere. Or maybe in some other place/dialog/popup (?).
3. Tests?

*P.S.* Thanks for such awesome product. It does definitely have potential.

### CODE REVIEW

**Comment by jeremycryan** [comment]
Looks great. Made one minor change so the GUI printout reflects the new file name.

**Comment by zugzug90** [comment]
> Looks great. Made one minor change so the GUI printout reflects the new file name.

Cool. Thank you. Btw, how can I make a new executable build?

**Comment by jeremycryan** [comment]
For generating the executable, I use pyinstaller. There's currently a .spec file that has settings and whatnot, which is currently in the .gitignore (and consequentially not in Github). It's probably just worth having that online and including directions for building an executable in the readme.

**Comment by jeremycryan** [comment]
In the meantime, if you want to try generating an EXE for yourself, you can run ```pyinstaller --onefile --noconsole music_gen_gui.py```. You may have to move the images folder and the font file into the new directory that pyinstaller generates.

**Comment by zugzug90** [comment]
@jeremycryan - Thanks for the info, I'll try these steps on my machine (maybe in the middle of the week).

.. Yeah, maybe it would be nice to have `how-to-build` section in `README.md`

**Pull request merged**
